dofile("mods/theme_christmas/effects/mushroom_cloud_snowflakes.lua")
dofile(path .. "/effects/util_dlc.lua")
fix_paths("mods/theme_christmas")
if not Effects then Effects = {} end
table.insert(Effects, 
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 3.5,
		InitialSize = 100,
		ExpansionRate = -2000,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1 = { 130, 110, 255, 128 },
		Colour2 = { 0, 0, 255, 0 },
	}
)
table.insert(Effects, 
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.08,
		InitialSize = 35,
		ExpansionRate = -1000,
		Angle = 90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 200,
		Colour1 = { 120, 100, 255, 160 },
		Colour2 = { 120, 100, 255, 160 },
	}
)
table.insert(Effects, 
	{
		Type = "sprite",
		TimeToTrigger = 0.16,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.04,
		InitialSize = 30,
		ExpansionRate = -1000,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 200,
		Colour1 = { 255, 255, 255, 200 },
		Colour2 = { 70, 30, 255, 90 },
	}
)
table.insert(Effects, 
	{
		Type = "sprite",
		TimeToTrigger = 0.32,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.08,
		InitialSize = 20,
		ExpansionRate = -1000,
		Angle = -90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 200,
		Colour1 = { 90, 60, 255, 200 },
		Colour2 = { 40, 0, 255, 90 },
	}
)
table.insert(Effects,
	{ -- glow sprite that follows the fireball
		Type = "sprite",
		LocalPosition = { x = 0, y = 0, z = -64 },
		LocalVelocity = { x = 0, y = 50, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0.0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 16,
		InitialSize = 30,
		ExpansionRate = -200,
		Angle = 90,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		Colour1Time = 0.03,
		Colour2Time = 1,
		Colour1 = { 90, 60, 255, 250 },
		Colour2 = { 60, 40, 255, 0 },
	})
table.insert(Effects, 	
	{
		Type = "shake",
		PlayForEnemy = true,
		FalloffStart = 3000,
		FalloffEnd = 10000,
		TimeToTrigger = 0,
		TimeToLive = 0.45,
		Magnitude = 300,
	}
)