if not Effects then Effects = {} end
table.insert(Effects,
{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.5,
		InitialSize = 1,
		ExpansionRate = 2000,
		Angle = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		KillParticleOnEffectCancel = true,
		Colour1 = { 40, 40, 255, 90 },
		Colour2 = { 40, 40, 255, 90 },
})
table.insert(Effects,
{
		Type = "sprite",
		TimeToTrigger = 0.5,
		LocalPosition = { x = 0, y = 0, z = -100 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 1.25,
		InitialSize = 12,
		ExpansionRate = -600,
		Angle = 0,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 0,
		KillParticleOnEffectCancel = true,
		Colour1 = { 40, 40, 255, 90 },
		Colour2 = { 40, 40, 255, 50 },
})
