table.insert(Effects,	
	{
		Type = "shake",
		PlayForEnemy = true,
		FalloffStart = 1000,
		FalloffEnd = 4000,
		TimeToTrigger = 0,
		TimeToLive = 0.2,
		Magnitude = 40,
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0,
		LocalPosition = { x = 0, y = 0, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 1.0,
		Sprite = path .. "/effects/media/bloom1.png",
		Additive = true,
		TimeToLive = 0.2,
		InitialSize = 5.8,
		ExpansionRate = -300,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 80,
		Colour1 = { 140, 180, 255, 255 },
		Colour2 = { 90, 140, 255, 180 },
	})
table.insert(Effects,
	{
		Type = "sprite",
		TimeToTrigger = 0.12,
		LocalPosition = { x = 0, y = 0, z = 0 },
		LocalVelocity = { x = 0, y = 0, z = 0 },
		Acceleration = { x = 0, y = 0, z = 0 },
		Drag = 1.0,
		Sprite = path .. "/effects/media/bloom3.png",
		Additive = true,
		TimeToLive = 0.24,
		InitialSize = 11,
		ExpansionRate = -300,
		AngularVelocity = 0,
		RandomAngularVelocityMagnitude = 80,
		Colour1 = { 140, 180, 255, 240 },
		Colour2 = { 90, 140, 255, 30 },
	})